python3 demos/demo.py --demo-video /home/shared/wrf/siam-mot/smd_dataset/raw_data/test/MVI_0799_VIS_OB/MVI_0799_VIS_OB.avi --output-path VisualOutputs/MVI_0799_VIS_OB
python3 demos/demo.py --demo-video /home/shared/wrf/siam-mot/smd_dataset/raw_data/test/MVI_0801_VIS_OB/MVI_0801_VIS_OB.avi --output-path VisualOutputs/MVI_0801_VIS_OB
python3 demos/demo.py --demo-video /home/shared/wrf/siam-mot/smd_dataset/raw_data/test/MVI_1451_VIS_Haze/MVI_1451_VIS_Haze.avi --output-path VisualOutputs/MVI_1451_VIS_Haze
python3 demos/demo.py --demo-video /home/shared/wrf/siam-mot/smd_dataset/raw_data/test/MVI_1452_VIS_Haze/MVI_1452_VIS_Haze.avi --output-path VisualOutputs/MVI_1452_VIS_Haze
python3 demos/demo.py --demo-video /home/shared/wrf/siam-mot/smd_dataset/raw_data/test/MVI_1479_VIS/MVI_1479_VIS.avi --output-path VisualOutputs/MVI_1479_VIS
python3 demos/demo.py --demo-video /home/shared/wrf/siam-mot/smd_dataset/raw_data/test/MVI_1584_VIS/MVI_1584_VIS.avi --output-path VisualOutputs/MVI_1584_VIS
python3 demos/demo.py --demo-video /home/shared/wrf/siam-mot/smd_dataset/raw_data/test/MVI_1610_VIS/MVI_1610_VIS.avi --output-path VisualOutputs/MVI_1610_VIS
python3 demos/demo.py --demo-video /home/shared/wrf/siam-mot/smd_dataset/raw_data/test/MVI_1615_VIS/MVI_1615_VIS.avi --output-path VisualOutputs/MVI_1615_VIS
python3 demos/demo.py --demo-video /home/shared/wrf/siam-mot/smd_dataset/raw_data/test/MVI_1622_VIS/MVI_1622_VIS.avi --output-path VisualOutputs/MVI_1622_VIS
python3 demos/demo.py --demo-video /home/shared/wrf/siam-mot/smd_dataset/raw_data/test/MVI_1626_VIS/MVI_1626_VIS.avi --output-path VisualOutputs/MVI_1626_VIS
python3 demos/demo.py --demo-video /home/shared/wrf/siam-mot/smd_dataset/raw_data/test/MVI_1645_VIS/MVI_1645_VIS.avi --output-path VisualOutputs/MVI_1645_VIS
python3 demos/demo.py --demo-video /home/shared/wrf/siam-mot/smd_dataset/raw_data/test/MVI_1646_VIS/MVI_1646_VIS.avi --output-path VisualOutputs/MVI_1646_VIS
python3 demos/demo.py --demo-video /home/shared/wrf/siam-mot/smd_dataset/raw_data/test/MVI_1486_VIS/MVI_1486_VIS.avi --output-path VisualOutputs/MVI_1486_VIS
